### ISSUE TITLE
Validation on bio form

### ISSUE THREAD

**Issue by szech** [JustinWingChungHui/MyFamilyRoot#53]
Can enter death year < than birth year..... 
We would need to make an exception for death year =0 (if we want to keep that convention)

**Comment by JustinWingChungHui** [comment]
Would make mistakes more difficult to correct e.g.
Having Birth Year 03/02/1982 and Death Year 04/02/1982, and I want to change them both to one year later
This means you would have to change the death year first otherwise the validation would kick.  I think this is just as unusable but with more complexity.
